### ISSUE TITLE
guide

### ISSUE THREAD

**Issue by OlivierJM** [Mellorison/_0rison#2]
Awesome stuff @Mellorison 🚀 🚀 🚀

I wasn't able to test it out as I don't have a PC(If meant windows) would you add a section on how to run the game, or if it is an installer can you link it the readme or you could also create a release if you are planning to have future versions of this then you can attach either tarballs to the release or the actual installer which someone can easily use to install.

Thanks for sharing this.

**Comment by Mellorison** [comment]
Thank you @OlivierJM . Well the incentive is to get the user to be more practical by building his/her own game. I will be putting up a tutorial on how to build a demo game before the end of the week. But for now, I have put up tutorials on the Data structures and features of the Framework which you could also use to build your own game from the ground up using the pre-loaded assets. Hope this helps. Also... an installer is a feature I'll add to my roadmap. Thanks again.

**Comment by OlivierJM** [comment]
Ohhh Yeah I see, thanks for the explanation.

**Comment by Mellorison** [comment]
Tutorials are available here: https://danieltumelo.teammakkon.com/getting-started/ . Kindly spread the word to anyone you think would be interested in contributing to this project. :-)

**Comment by OlivierJM** [comment]
Sure I will share it. 

Thanks
